typography_spectrum: 0.5291934497654438
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4665336112957448
  lightness: 0.5411639621015638
  saturation: 0.11611340125091374
  rhythmicContrast: 0.5062796815764159
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6167875430546701
analytics:
  google: null
  facebook: null
  twitter: null
name: An Act of Free Will
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: An Act of Free Will
purpose: []
